### ISSUE TITLE
Use real machine test crash：   Reason: image not found

### ISSUE THREAD

**Issue by CenLei518** [mdiep/MMMarkdown#102]
dyld: Library not loaded: @rpath/MMMarkdown.framework/MMMarkdown
  Referenced from: /var/containers/Bundle/Application/0E62B54F-7949-4ABA-8669-6BB4869C70D8/MarkdownDemo092701.app/MarkdownDemo092701
  Reason: image not found

![2016-04-26 1 02 04](https://cloud.githubusercontent.com/assets/9047094/14807413/243764f2-0baf-11e6-9296-5e28bf0bda87.png)

**Comment by mdiep** [comment]
You haven't properly configured your application to work with MMMarkdown. Most likely, you haven't copied MMMarkdown into your application bundle.

**Comment by CenLei518** [comment]
This would solve the

![qq20160426-0](https://cloud.githubusercontent.com/assets/9047094/14820876/18691e8a-0bfb-11e6-952f-6054e91373c7.png)
