### ISSUE TITLE
URL parsing failure

### ISSUE THREAD

**Issue by albertbori** [mdiep/MMMarkdown#114]
The following link:
https://medium.com/@philipla/the-two-types-of-product-virality-8ae744b1c4d7
gets rendered as:
![screen shot 2016-11-08 at 10 50 33 am](https://cloud.githubusercontent.com/assets/1742709/20110337/3892c842-a5a1-11e6-9922-7f0742589074.png)

**Comment by mdiep** [comment]
Care to open a pull request? It should be easy to add `@` as a valid auto linking character (with a test).
