### ISSUE TITLE
Get the Markdown text back from UITextView

### ISSUE THREAD

**Issue by danmaia17** [mdiep/MMMarkdown#119]
I convert the markdown to HTML and put it in a UITextView, i need get the markdown text back from UITextView, how i get this text back?

Obs: I can´t get html text from UITextView and convert it in MarkDown back, because when i get the html from UITextView, the html have CSS styles, so i can´t convert in markdown.

**Comment by mdiep** [comment]
You can't. You'll need to save the markdown separately.

**Comment by danmaia17** [comment]
Thanks.
