### ISSUE TITLE
Markdown of OL with UL is outputted in not Good HTML.

### ISSUE THREAD

**Issue by lenlenlen** [mdiep/MMMarkdown#15]
Thank you published a very nice program.
Please let me bug reports today.

In the case of this example, MMMarkdown is not correctly changed into HTML. 

【Example Markdown】
<pre>1.test
2.tester
3.testing

*boxing
*kick boxing
*karate</pre>

【Result HTML】
<pre>
&lt;ol&gt;
&lt;li&gt;test&lt;/li&gt;
&lt;li&gt;tester&lt;/li&gt;
&lt;li&gt;&lt;p&gt;testing&lt;/p&gt;&lt;/li&gt;
&lt;li&gt;&lt;p&gt;boxing&lt;/p&gt;&lt;/li&gt;
&lt;li&gt;kick boxing&lt;/li&gt;
&lt;li&gt;karate&lt;/li&gt;
&lt;/ol&gt;
</pre>

【Result that I want is this.】
<pre>
&lt;ol&gt;
&lt;li&gt;test&lt;/li&gt;
&lt;li&gt;tester&lt;/li&gt;
&lt;li&gt;testing&lt;/li&gt;
&lt;/ol&gt;

&lt;ul&gt;
&lt;li&gt;boxing&lt;/li&gt;
&lt;li&gt;kick boxing&lt;/li&gt;
&lt;li&gt;karate&lt;/li&gt;
&lt;/ul&gt;
</pre>

I hope that it will be fixed.
Thanks for reading so far.

**Comment by albertbori** [comment]
I ran into this issue as well. Here in github, the following markdown:

```
- Cool
- Neat

1. Item 1
1. Item 2
```
Results in:
- Cool
- Neat

1. Item 1
1. Item 2

But when I run it through MMMarkdown, I get:

```
<ul>
<li>Cool</li>
<li><p>Neat</p>
</li>
<li><p>Item 1</p>
</li>
<li>Item 2</li>
</ul>
```

(Aside: Unfortunately, in both, I get that stray paragraph tag in some of the items, which cases extra spacing within list items.)

**Comment by SerenadeX** [comment]
Seeing this as well.  It works if you start with unordered lists and follow with an ordered list and vice versa.  Is progress being made on this?

**Comment by mdiep** [comment]
I haven't worked on this at all, but now that CommonMark is rendering this as two separate lists, I'll take a look at updating the behavior.
