### ISSUE TITLE
Podspec needs to be updated

### ISSUE THREAD

**Issue by adamkovica** [mdiep/MMMarkdown#18]
May I ask you to update pod spec based on the latest changes (removed static library, added 64 bit support). Thank you very much.

**Comment by iosdev-republicofapps** [comment]
@dirtyhenry @adamkovica  I maintain the pod spec (as a volunteer and fellow Cocoapods user of MMMarkdown).  I just updated the spec to 0.4.2 and published it.

Can you please outline the changes in the spec you'd like to see and I'd be happy to help make them.  There's nothing currently in the pod spec that deals with 32- or 64-bit so I don't see why there would be a 64-bit issue but I'm a pod spec noob so I could be wrong.

**Comment by iosdev-republicofapps** [comment]
Oh, actually, I think I have synced your changes, @dirtyhenry , see https://github.com/iosdev-republicofapps/MMMarkdown/blob/master/MMMarkdown.podspec.json
