### ISSUE TITLE
mmmarkdown misses link

### ISSUE THREAD

**Issue by briomusic** [mdiep/MMMarkdown#22]
In the following example, the link is not recognised:

`Use CRB65 score to help guide and review:<sup>[1](/notes/community-acquired pneumonia/#1)</sup> Each scores 1: Confusion (AMT<8); Respiratory rate >30/min; Age >65; BP systolic <90 or diastolic <= 60;`

I tried in Mou, where it works fine. Thanks for fixing the last bug btw!

**Comment by mdiep** [comment]
CommonMark doesn't recognize that link. Since I'm trying to standardize on CommonMark's behavior, I'm going to close this.
