### ISSUE TITLE
Best approach for custom substitutions of block quote content?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [mdiep/MMMarkdown#46]
Hey,

I'm translating Markdown to HTML using MMMarkdown and it's working well so far.  What I'd like to do though is replace instances of "--" with "&mdash;" inside of block quotes so that the user gets the nifty long single quote.

I only want to do this inside block quotes though.  What do you think is the best way to do this?  In `MMGenerator._generateHTMLForElement:inDocument:HTML:location:` or somewhere in `MMParser`?

I could do this with my own custom subclass of MMGenerator, but overriding a private method is risky and could break with future updates.  Another alternative would be to pass in some blocks that could preprocess the naked text of each element.

What do you think?  :-)

Thanks!

**Comment by mdiep** [comment]
You would really be better off using something like Ruby's [html-pipeline](https://github.com/jch/html-pipeline). (But I'm not sure if there's a similar project for Objective-C.)

Failing that, the easiest solution would be to subclass `MMGenerator`. That probably won't work forever, but if/when it changes it will probably be easy for you to change as well.

**Comment by iosdev-republicofapps** [comment]
I think I'll just try and subclass MMGenerator for now.  I'll just have to be careful when merging in new versions of MMMarkdown, but I can live with that for now.

Would you be interested in a pull request to add a generic API for this to MMMarkdown if I were to come up with something more general purpose?

Thanks!

**Comment by mdiep** [comment]
I'm not interested in adding an API for this right now because I'd like to redesign the parser and generator to be expandable. But thanks for the offer! :sparkles:

**Comment by iosdev-republicofapps** [comment]
Totally understood and you're welcome.  :-)
