### ISSUE TITLE
Parsing of tab/4space-delimited code blocks differs from github parsing and other markdown editors

### ISSUE THREAD

**Issue by iosdev-republicofapps** [mdiep/MMMarkdown#52]
Hi,

The Markdown "standard" is a bit vague about this, but most Markdown parsers (e.g., Github's issues markdown parser, Markdown Pro, etc) will only honor a tab/4space-delimited code block if the block is preceded by an empty line (or a line containing nothing but whitespace).  So for example

The following does NOT produce a code block in GitHub issues or Markdown Pro:
    var x = 2;

But it DOES produce a code block in MMMarkdown.

If you look at the actual HTML source for the "standard" at [daringfireball](http://daringfireball.net/projects/markdown/syntax#precode) it shows:
```
<p>To produce a code block in Markdown, simply indent every line of the
block by at least 4 spaces or 1 tab. For example, given this input:</p>

<pre><code>This is a normal paragraph:

    This is a code block.
</code></pre>
```
Notice how there's a blank line before the tab/4space-delimited code block in Gruber's example.

So it seems like to work the same as Github issues markdown parsing and other Markdown editors, MMMarkdown should:
- NOT create a code block for a tab/4space-delimited code block unless:
    - the code block comes at the very beginning of the document or
    - the code block is preceded by a blank line or a line composed of nothing but whitespace

It seems like the presence of a blank or whitespace-only line after the code block doesn't impact Github or Markdown Pro parsing.

I guess this kind of makes sense since block elements like paragraphs are normally separated by blank/whitespace-only lines in Markdown.  Further, it's legal to have 4 leading spaces or a tab in a line of a paragraph, so I guess the blank line is needed to indicate that the paragraph is done and over.

Is it possible to update MMMarkdown to behave more like Github issues Markdown parsing in this case?

Or alternatively, when I add the other flags about turning off Setext headers, could I add a flag also to disable tab/4space-delimited code blocks (since these code blocks are harder to syntax highlight using regexes than are fenced code blocks)?

I'm happy to help in whatever way I can.  Please let me know if you need a test case to repro this.  Here are some sample tests cases below:
```
NSString *shouldNotProduceACodeBlock1 = @"Some text.\n    NSString *foo;";
NSString *shouldNotProduceACodeBlock2 = @"Some text.\n\tNSString *foo;";
NSString *shouldProduceACodeBlock1 = @"Some text.\n\n    NSString *foo;";
NSString *shouldProduceACodeBlock2 = @"Some text.\n\n\tNSString *foo;";
NSString *shouldProduceACodeBlock3 = @"Some text.\n \n    NSString *foo;";
NSString *shouldProduceACodeBlock4 = @"Some text.\n\t\n\tNSString *foo;";
```

**Comment by mdiep** [comment]
> But it DOES produce a code block in MMMarkdown.

I'm not seeing this. :confused:

This input:

```
The following does NOT produce a code block in GitHub issues or Markdown Pro:
    var x = 2;
```

produces this in MMMarkdown:

```
<p>The following does NOT produce a code block in GitHub issues or Markdown Pro:
    var x = 2;</p>
```

Do you have any extensions turned on? A working test case would be very helpful.

**Comment by iosdev-republicofapps** [comment]
Hi,

Thanks for getting back to me.

I do have extensions turned on.  I was able to produce this at work but now not at home.  Let check again at work and get back to you by Tuesday.

Sorry for the potential false alarm.

Have a good weekend!

**Comment by iosdev-republicofapps** [comment]
I can't repro this so I guess we can close it for now.  :-)

**Comment by mdiep** [comment]
:tada:
