### ISSUE TITLE
Lack of support for image links

### ISSUE THREAD

**Issue by albertbori** [mdiep/MMMarkdown#56]
The following markdown should produce an image link:
```
[![Werewolf Cop](http://ecx.images-amazon.com/images/I/51UENmW1sgL._SL175_.jpg)](http://www.amazon.com/exec/obidos/ASIN/1605986984/ref=nosim/founders-20)
```

Like so:
[![Werewolf Cop](http://ecx.images-amazon.com/images/I/51UENmW1sgL._SL175_.jpg)](http://www.amazon.com/exec/obidos/ASIN/1605986984/ref=nosim/founders-20)

Instead, it produces the following:
[\!\[Werewolf Cop\]\(http://ecx.images-amazon.com/images/I/51UENmW1sgL._SL175_.jpg\)](http://www.amazon.com/exec/obidos/ASIN/1605986984/ref=nosim/founders-20)

**Comment by mdiep** [comment]
Thanks for the report! This is definitely a bug. I'll try to look into it sometime this week.

**Comment by mdiep** [comment]
I fixed this and created a new release (0.4.2) with the fix. :sparkles:

**Comment by albertbori** [comment]
Excellent! Thank you so much!

Mind bumping the [cocoapod version](https://cocoapods.org/pods/MMMarkdown)?

**Comment by mdiep** [comment]
I don't use CocoaPods or have an interest in maintaining a spec. So someone else will need to do it. Sorry!

**Comment by albertbori** [comment]
Ok, I submitted a pull request to CocoaPods / Specs: https://github.com/CocoaPods/Specs/pull/13056

**Comment by iosdev-republicofapps** [comment]
I maintain the CocoaPods spec for this pod (as a volunteer) so I'll try to get out a release soon ...

**Comment by iosdev-republicofapps** [comment]
@albertbori I just updated and pushed a 0.4.2 pod spec.  You might need to do `pod repo update`.  Then:
```
shell> pod search MMMarkdown

-> MMMarkdown (0.4.2)
   An Objective-C static library for converting Markdown to HTML.
   pod 'MMMarkdown', '~> 0.4.2'
   - Homepage: https://github.com/mdiep/MMMarkdown
   - Source:   https://github.com/mdiep/MMMarkdown.git
   - Versions: 0.4.2, 0.4.1, 0.4, 0.3, 0.2.3, 0.2.1 [master repo]
```
So the latest 0.4.2 version is pushed to CocoaPods.  Enjoy!

**Comment by albertbori** [comment]
Thanks for updating that. I'd never worked with updating a repo that didn't have its own podspec.
