### ISSUE TITLE
libMMMarkdown-iOS.a is showing red in Xcode

### ISSUE THREAD

**Issue by amitch001** [mdiep/MMMarkdown#61]
Hi,
When I add libMMMarkdown-iOS.a in include libraries in my project ---> It appears as red. it means there is not library like this. Please help me how to include "libMMMarkdown-iOS.a" library in my project. 

In your MMMarkdown github folder also I am unable to find "libMMMarkdown-iOS.a" library. Please help me!!

**Comment by mdiep** [comment]
MMMarkdown no longer includes a pre-built iOS binary. You'll need to follow the instructions in the [setup](https://github.com/mdiep/MMMarkdown#setup) section of the README.

**Comment by amitch001** [comment]
Hi Mdiep,
Thank you so much for your swift response!!

I followed the steps (4 steps) provided in step guide. I added MMMarkdown-iOS.a in my projects Build Phase Target Dependencies also. I also followed Apple documentation on how to add static libraries in Xcode. 

I think I am doing wrong in step 4. Can you please tell me what I have to enter in "Header Search Paths" in Build settings of my projects. Do i have to enter the path of MMMarkdown-iOS.a located in my computer? I have no experience in this and I googled a lot to find out about it but haven't found a single document which explained about it clearly. Can you please tell me what I have to enter in Header search path for "$(CONFIGURATION_BUILD_DIR)/MMMarkdown-iOS/public/" ? 

Thanks again,
Waiting for your response

**Comment by mdiep** [comment]
1. Open your project in Xcode
2. Press ⌘1 to open the sidebar
3. Click on your project in the sidebar
4. Click on the "Build Settings" tab
5. In the search field, type "search"
6. Under search paths, you should see a row labeled "Header Search Paths"
7. Edit that row and add the value `$(CONFIGURATION_BUILD_DIR)/MMMarkdown-iOS/public/`

**Comment by amitch001** [comment]
Hi mdiep,
1. I followed the steps clearly. Please see the attached screenshot. 
2. I am getting an error message whenever I do #import <MMMarkdown/MMMarkdown.h> 
  Error message : MMMarkdown/MMMarkdown.h file not found. Please see the attached screenshots. 

What I am doing wrong? Please help me
![e1](https://cloud.githubusercontent.com/assets/531024/7315871/455d7096-ea8f-11e4-816e-25b04da758bd.png)

![e2](https://cloud.githubusercontent.com/assets/531024/7315828/c8f8715e-ea8e-11e4-9e7c-6cd4e1967ba9.png)
![e3](https://cloud.githubusercontent.com/assets/531024/7315826/c8e039fe-ea8e-11e4-86c9-372460529f95.png)
![e4](https://cloud.githubusercontent.com/assets/531024/7315829/c9155d78-ea8e-11e4-89ec-4fde31ec0af2.png)
![e5](https://cloud.githubusercontent.com/assets/531024/7315827/c8e68c82-ea8e-11e4-8d0f-64d7710adbe5.png)

**Comment by mdiep** [comment]
Have you tried building? The library will be red until you build.
