### ISSUE TITLE
Line breaks weird behavior.

### ISSUE THREAD

**Issue by njuri** [mdiep/MMMarkdown#65]
Input:
Lorem ipsum.\n
\n
Lorem ipsum.
Output:
<"p>Lorem ipsum.<"/p>
<"p>Lorem ipsum.<"/p>

Input:
Lorem ipsum.\n
\n
\n
Lorem ipsum.
Output:
<"p>Lorem ipsum.<"/p>
<"p>Lorem ipsum.<"/p>

So regardless of how much line breaks are entered, output is markdown without empty line.

P.S There're no quotes inside paragraph tags in output, I've put them there to prevent github markdown parsing.

**Comment by mdiep** [comment]
So your input looks like this? (You can [use Markdown](https://guides.github.com/features/mastering-markdown/) to tell GitHub that the input is code to render it as-is.)

```
Lorem ipsum.


Lorem ipsum.
```

And your output is like this?

```
<p>Lorem ipsum.</p>
<p>Lorem ipsum.</p>
```

If so, that looks correct to me. If you want an empty line between the paragraphs, you probably need to use CSS or something to adjust the spacing. How are you displaying the output?

**Comment by njuri** [comment]
Thanks for answering, but in GitHub (e.g writing readme) you can put two line breaks (as in my input, you understood it correctly) and get empty line between two paragraphs.

**Comment by mdiep** [comment]
The empty line you get on GitHub is the result of the to `<p>` tags in the above output. You can change how those are rendered to display or not display an empty line between the paragraphs.

**Comment by njuri** [comment]
So I tried to use an MMMarkdownExtensionsGitHubFlavored extension, but it still creates just two paragraphs next to each other without empty line between.

**Comment by mdiep** [comment]
You don't need to use `MMMarkdownExtensionsGitHubFlavored`.

This:

```
<p>Lorem ipsum.</p>
<p>Lorem ipsum.</p>
```

should render with a blank line between the paragraphs. It is the correct output. If there's not a blank line, then you need to change how the output is displayed.

**Comment by njuri** [comment]
Look at this, I've added
```swift
textView.text.stringByReplacingOccurrencesOfString("\n", withString:" </br>")
```
Instead of just
```swift
textView.text
```

And this did exactly what I wanted, so since it wasn't library issue, I think this issue could be closed.
