### ISSUE TITLE
Auto-URL parsing failiure

### ISSUE THREAD

**Issue by albertbori** [mdiep/MMMarkdown#77]
Automatic URL parsing leaves out critical bits of the url. It looks like it stops parsing the URL at the `=` sign.

Example Markdown:
> Here is a good 50 Apple Watch Tip and Tricks tutorial: https://www.youtube.com/watch?v=tiAY33fNGZ4

Result: 

<img width="354" alt="screen shot 2015-07-30 at 5 31 25 pm" src="https://cloud.githubusercontent.com/assets/1742709/9229935/c9124508-40dc-11e5-8ef5-a7d789ca4b67.png">

**Comment by mdiep** [comment]
Thanks. This was fixed in #59.
