### ISSUE TITLE
HTMLStringWithMarkdown returning null string in iPhone Device, while working in simulator

### ISSUE THREAD

**Issue by PraveenNess** [mdiep/MMMarkdown#78]
Following instruction has been followed to add MMMarkDownLibrary in IOS Project. And run the build in iPhone-6(IOS-8.4.1). "HTMLStringWithMarkdown" returning the Nil string. 

[MMMarkdown HTMLStringWithMarkdown:markDownString extensions:MMMarkdownExtensionsAutolinkedURLs error:NULL];

Instruction to add MMMarkdown in IOS app - 
Add MMMarkdown as a git submodule. (git submodule add https://github.com/mdiep/MMMarkdown <path>)
Add MMMarkdown.xcodeproj to your project or workspace
Add MMMarkdown.framework to the ”Link Binary with Libraries" section of your project's “Build Phases”.
Add MMMarkdown.framework to a ”Copy Files” build phase that copies it to the Frameworks destination.

**Comment by mdiep** [comment]
What are you passing as the markdown string?
