### ISSUE TITLE
Converting Issue?

### ISSUE THREAD

**Issue by Jusung** [mdiep/MMMarkdown#79]
Hello, Matt Diephouse.

Thanks for developing this good framework.
I've been using this framework well. 

Recently I've got a report from a user about Markdown.
He said he can't use table syntax in the app which is using this Markdown Framework.
I wonder if this MMarkdown framework supports table relevant converting.
I think it is, right? Because I can see some Unit test code related to table source in this code. 

And I've found one more thing which is not working well.

The tutorial says like following

#import <MMMarkdown/MMMarkdown.h>

NSString *markdown   = @"'~'~'Mistaken'~'~'";
NSString *htmlString = [MMMarkdown HTMLStringWithMarkdown:markdown extensions:MMMarkdownExtensionsGitHubFlavored error:NULL];
// Returns @"'<'p'>'<'d'e'l'>'Mistaken'<'/'d'e'l'><'/'p'>"

@"'~'~'Mistaken'~'~'" is supposed to @"'<'p'>'<'del'>'Mistaken'<'/'del'><'/p'>" as a result
But in my case @"'~'~'Mistaken'~'~'" is returned as a result.
*I added ' to every words which could be used for converting to prevent being converted to formatting word.

Did I missing something? Can you help me out?

Regards,
Jusung

**Comment by mdiep** [comment]
There's a test for this, and I just validated locally that the correct HTML is returned. So you must have an error somewhere in your code. :confused:

**Comment by Jusung** [comment]
Thanks for the reply.

I figured out the reason why my code didn't work.
I used "[MMMarkdown HTMLStringWithMarkdown:markdownString error:&error];"
which is normal method for standard Markdown.
But when I used "[MMMarkdown HTMLStringWithMarkdown:markdownString extensions:MMMarkdownExtensionsGitHubFlavored error:&error];" which has extensions, the converting worked well.

Thank you again for your time!
