### ISSUE TITLE
Missing block quote?

### ISSUE THREAD

**Issue by messiach** [mdiep/MMMarkdown#80]
Block quoting with '>' seems not to work.

Example:

Markdown:
    > This is a quote from a previous reply or comment.
    Now this is my response to that quote.

Should be rendered as:
> This is a quote from a previous reply or comment.
Now this is my response to that quote.

MMMarkdown results are the same - the block quote isn't handled, it's simply reprinted as is.

**Comment by mdiep** [comment]
With this input:

```
> This is a quote from a previous reply or comment.
Now this is my response to that quote.
```

I get this output:

```
<blockquote>
<p>This is a quote from a previous reply or comment.
Now this is my response to that quote.</p>
</blockquote>
```

This matches the behavior of GitHub.com and [most other Markdown implementations](http://johnmacfarlane.net/babelmark2/?normalize=1&text=%3E+This+is+a+quote+from+a+previous+reply+or+comment.%0ANow+this+is+my+response+to+that+quote.). Are you getting different output? Or are you expecting different output?

**Comment by messiach** [comment]
Sorry this turned out to be an implementation detail - the text I have to convert has html entities (&gt;).  MMMarkdown will skip those unless I decode them first - but of course I can't set the attributedText property of my UITextView unless I convert again what's provided by MMMarkdown (which ends up looking incorrect - line breaks missing - and is slow).
