### ISSUE TITLE
Not converting markdown to html for Table

### ISSUE THREAD

**Issue by hardikpithadia** [mdiep/MMMarkdown#83]
Hello,
I am using XCode 7.0 & using this library. I am trying to convert markdown to HTML string for Table.
I am passing markdown tag for table as per the following.

| Tables             | Are                  | Cool    |
| -------------        |:-------------:       | -----:     |
| col 3 is            | right-aligned | $1600  |
| col 2 is            | centered        |   $12    |
| zebra stripes | are neat         |    $1     |

But, Its not giving me proper HTML Output as per the following

```
<table><thead><tr></tr></thead><tbody><tr></tr></tbody></table><p>|Tables|Are|Cool|<br />
| ------------- | : ------------- : | ----- : |<br />
| col 3 is | right-aligned | $1600 |<br />
| col 2 is | centered | $12 |</p>
```

**Comment by mdiep** [comment]
Can you show the code you're using that calls MMMarkdown?

**Comment by mdiep** [comment]
Are you actually adding the `<table>` and other HTML tags in your input?

**Comment by hardikpithadia** [comment]
No I'm not adding <table> tag. I am simply passing Markdown tag for table

**Comment by hardikpithadia** [comment]
I am passing following string to markdown library for get HTML string
NSString *stringToWrite = @"|Tables|Are|Cool|\n| ------------- | : ------------- : | ----- : |\n| col 3 is | right-aligned | $1600 |\n| col 2 is | centered | $12 |";

**Comment by hardikpithadia** [comment]
I will be really Thankful to you, Please help me out.
Thank you

**Comment by mdiep** [comment]
Are you using `[MMMarkdown HTMLStringWithMarkdown:extensions:error:]` and turning on the tables extension?

**Comment by hardikpithadia** [comment]
yes, My Code is.. 

NSString *stringToWrite = @"|Tables|Are|Cool|\n| ------------- | : ------------- : | ----- : |\n| col 3 is | right-aligned | $1600 |\n| col 2 is | centered | $12 |";

NSString *htmlString = [MMMarkdown HTMLStringWithMarkdown:stringToWrite error:&error];

**Comment by hardikpithadia** [comment]
Okay.. I used the Method...
[MMMarkdown HTMLStringWithMarkdown:extensions:error:]

It seems like its working..
Thank you for pointing out this method.

**Comment by Abingesera** [comment]
> Okay.. I used the Method... [MMMarkdown HTMLStringWithMarkdown:extensions:error:]
> 
> It seems like its working.. Thank you for pointing out this method.

Hi bro, What component are you using to display HTML-formatted text? I tried both YYLabel and DTAttributedLabel, and both have poor rendering for table styles. Thanks
