### ISSUE TITLE
Failure to convert blockquotes

### ISSUE THREAD

**Issue by albertbori** [mdiep/MMMarkdown#84]
#### The snippet:
```
This is a format thing.

> Test quote

**Cool.**
```
#### Displays as:

This is a format thing.

\> Test quote

**Cool.**

#### Should display as:

This is a format thing.

> Test quote

**Cool.**

#### Sample screenshot from device:

![screen shot 2015-10-21 at 11 40 35 am](https://cloud.githubusercontent.com/assets/1742709/10652682/d280ec6e-7815-11e5-9677-681e7d4e85d4.png)

**Comment by mdiep** [comment]
I see this output, which looks correct:

```
<p>This is a format thing.</p>
<blockquote>
<p>Test quote</p>
</blockquote>
<p><strong>Cool.</strong></p>
```

**Comment by albertbori** [comment]
![This is not the bug you are looking for](http://cdn.meme.am/instances/400x/61532904.jpg)
