### ISSUE TITLE
Could you release a new version?

### ISSUE THREAD

**Issue by iosdev-republicofapps** [mdiep/MMMarkdown#87]
Hey,

I had a user ask me to add tvos support to the CocoaPods pod spec.  However, cocoa pods won't let me push a new pod spec unless I increment the version number.  However, I want to keep the pod spec version the same as the MMMarkdown version.

I see you've made a few changes since 0.5.  Any chance you could release 0.5.1 of MMMarkdown and then I can push that new version's pod spec and include the tvos version in it?  :-)

Thanks!

**Comment by mdiep** [comment]
I just released 0.5.1 with a few more fixes and targets for tvOS and watchOS.

**Comment by iosdev-republicofapps** [comment]
Thanks!  I'll rev the podspec tonight.
