### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by a1cooke** [mdiep/MMMarkdown#91]
It would be great if there was a public podspec available in order to include the library in a project.

I lean towards avoiding git submodules.

Many thanks in advance

**Comment by mdiep** [comment]
I believe @iosdev-republicofapps maintains a CocoaPods spec. I don't use CocoaPods, so I can't be responsible for maintaining a spec.

FWIW, MMMarkdown is compatible with [Carthage](https://github.com/Carthage/Carthage).

**Comment by iosdev-republicofapps** [comment]
@a1cooke MMMarkdown is in Cocoapods. I maintain the pod spec at [MMMarkdown.podspec.json](https://github.com/iosdev-republicofapps/MMMarkdown/blob/master/MMMarkdown.podspec.json) and I keep it in sync with MMMarkdown versions.  Is there something you need me to add?  The code that the pod spec pulls is directly from the [MMMarkdown repo](https://github.com/mdiep/MMMarkdown.git) so I don't need to sync my version.

**Comment by davecom** [comment]
Unfortunately having someone else maintain the podspec does mean the version reports incorrectly on CocoaPods.org when an update is not made to the file. For example, currently it shows as 0.5.1 on CocoaPods.org whereas the canonical version is 0.5.2. @mdiep I'd encourage you to add official support for CocoaPods even if you're not a CocoaPods user regularly. Popular and good libraries like this deserve as much as exposure as possible. The reality is, as you know, that CocoaPods is the de-facto dependency manager for most iOS/OS X developers.

**Comment by joelpresence** [comment]
@davecom  I maintain the CocoaPods spec for MMMarkdown.  I can bump it up to 0.5.2.  If people remind me when a new version of MMMarkdown comes out, I can bump it usually within a few days ... :-)

**Comment by iosdev-republicofapps** [comment]
@davecom I maintain the podspec for MMMarkdown.  If people ping me when a new version of MMMarkdown is released, I'm happy to update the podspec, usually within a few days ... :-)

**Comment by davecom** [comment]
@iosdev-republicofapps While, I appreciate what you're doing it's annoying for people to have to ping you though... Perhaps you can submit a pull request so @mdiep can easily take over.

**Comment by mdiep** [comment]
Sorry, but I have no interest in maintaining the podspec.

**Comment by iosdev-republicofapps** [comment]
@davecom I just pushed version 0.5.2 of the pod spec.

I proposed a PR to integrate the pod spec into the main repo but as he said above, @mdiep doesn't want to maintain the pod spec.  @mdiep is very generous to share MMMarkdown with us for free and I really appreciate all his handwork on this great Markdown parser.  If he doesn't want to include a pod spec, I think we should respect his wishes and thank him for releasing MMMarkdown.  We can maintain the pod spec ourselves.

If people let me know when a new version of MMMarkdown is released, I can usually release a new pod spec within a few days.

Is there some way I can listen for releases on this repo (e.g. so I could get an automatic email when a new release is made)?

Thanks.

**Comment by mdiep** [comment]
> Is there some way I can listen for releases on this repo (e.g. so I could get an automatic email when a new release is made)?

If you watch the repository (using the button at the top of the page), you'll get a notification for new issues, pull requests, and releases. This repository is pretty low-traffic, so that might not be too annoying for you.

Otherwise, I can try to remember to ping you when I create a new release.

**Comment by SerenadeX** [comment]
@iosdev-republicofapps can you push version 0.5.4 of the pod spec?

**Comment by iosdev-republicofapps** [comment]
Thanks for the heads up.  I’ll push tonight after work.

**Comment by iosdev-republicofapps** [comment]
Version 0.5.4 has been pushed:

```
shell> pod search MMMarkdown


-> MMMarkdown (0.5.4)
   An Objective-C static library for converting Markdown to HTML.
   pod 'MMMarkdown', '~> 0.5.4'
   - Homepage: https://github.com/mdiep/MMMarkdown
   - Source:   https://github.com/mdiep/MMMarkdown.git
   - Versions: 0.5.4, 0.5.2, 0.5.1, 0.5, 0.4.3, 0.4.2, 0.4.1, 0.4, 0.3, 0.2.3, 0.2.1 [master repo]
```

Thanks for your patience.
