### ISSUE TITLE
Using MMMarkdown, only system font will show bold or italicized text

### ISSUE THREAD

**Issue by selcukyucel** [mdiep/MMMarkdown#94]
Hi,
It works very nice unless I want to use my custom font. 

NSString *htmlString    = [MMMarkdown HTMLStringWithMarkdown:result extensions:MMMarkdownExtensionsGitHubFlavored error:nil];
    
TRIED TO CHANGE EXTENSIONS EACH OF THEM ASKING FOR.

    NSError *error = nil;
    
    NSAttributedString *attString = [[NSAttributedString alloc] initWithData:[htmlString dataUsingEncoding:NSUTF8StringEncoding] options:@{NSDocumentTypeDocumentAttribute:NSHTMLTextDocumentType, NSCharacterEncodingDocumentAttribute:@(NSUTF8StringEncoding)} documentAttributes:nil error:&error];
    
    if (error) {
        NSLog(@"Error: %@ %s %i", error.localizedDescription, __func__, __LINE__);
    } else {
        // Clear text view
       myTextView.text = @"";
        // Append the attributed string
        
      [myTextView.textStorage appendAttributedString:attString]; TRIED THIS
      
      myTextView.attributedText = attString;  TRIED THIS

    }

Any solution any approach to solve this would be great
Thanks.

**Comment by selcukyucel** [comment]
It is a uitextview in interface builder. font is set there, also I tried to change font in code. 
Not worked.

**Comment by mdiep** [comment]
I'm not sure. This isn't really MMMarkdown-specific.
