### ISSUE TITLE
Support for syntax highlighting

### ISSUE THREAD

**Issue by adamawolf** [mdiep/MMMarkdown#95]
Hello, I'd love to be able to use github-style syntax highlighting on fenced code blocks in MMMarkdown.

E.g.

```swift
let countInDozen: Int = 12
let sidesInTriangle: Int = 3
let lettersInEnglishAlphabet: Int = 26
```

vs.

```
let countInDozen: Int = 12
let sidesInTriangle: Int = 3
let lettersInEnglishAlphabet: Int = 26
```

Do you have any plans to add this feature? If not, how would you like to see it implemented were I to take this on?

**Comment by mdiep** [comment]
This is outside the scope of MMMarkdown. You can do this with another library after the Markdown step. Try using something like https://github.com/isagalaev/highlight.js.
