### ISSUE TITLE
Why is a new line character inserted after a <br /> tag in the HTML output

### ISSUE THREAD

**Issue by SerenadeX** [mdiep/MMMarkdown#98]
I'm looking at [this line](https://github.com/mdiep/MMMarkdown/blob/master/Source/MMSpanParser.m#L159) in particular.  Why would we want to include a `'\n'` character in the HTML if we have already put in a `<br />` tag?  `'\n'` characters do not render in HTML.

**Comment by SerenadeX** [comment]
I would open a PR removing this but I want to make sure that I understand the design of this before I start ripping things out.

**Comment by mdiep** [comment]
It makes the HTML marginally better to read. As you noted, `\n` characters do not render in HTML.

**Comment by SerenadeX** [comment]
Would it make sense then to have an option to not insert those characters?  In other words get all the HTML on one line?

**Comment by mdiep** [comment]
No, I think you should use a minifier if you're interested in that sort of behavior.
